STARTING_ELO = 1000
DATA_DIR = "data"

WIN, DRAW, LOSS = 1, 0.5, 0

KFACTOROPTION = 32
EXPONENTDENOMINATOR = 400
EXPONENTBASE = 10

# 5.      Elliot GILES    26 MAY 1994     GBR
LINE_INDEX_PLACE = 0
LINE_INDEX_NAME = 1
LINE_INDEX_COUNTRY = -1
LINE_INDEX_YEAR = -2
LINE_INDEX_MONTH = -3
LINE_INDEX_DAY = -4
